# Question 1

In [7]:
import numpy as np
from scipy import linalg

In [37]:
M = np.array([[1, 2, 3, 4], [2, 1, 4, 3]])
M = M.transpose()
M

array([[1, 2],
       [2, 1],
       [3, 4],
       [4, 3]])

## Compute the SVD of M

In [38]:
U, s, Vh = linalg.svd(M, full_matrices=False)

In [39]:
U

array([[-0.27854301,  0.5       ],
       [-0.27854301, -0.5       ],
       [-0.64993368,  0.5       ],
       [-0.64993368, -0.5       ]])

In [40]:
s

array([ 7.61577311,  1.41421356])

In [41]:
Vh

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

## Compute the eigenvalue decomposition of $M^TM$

In [71]:
evals, evecs = linalg.eigh(np.matmul(M.transpose(), M))

In [72]:
idx = evals.argsort()[::-1]
evals = evals[idx]
evecs = evecs[:, idx]

In [73]:
evals

array([ 58.,   2.])

In [74]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

## Based on the experiment and your derivations in part (c) and (d), do you see any correspondence between V produced by SVD and the matrix of eigenvectors Evecs roduced by eigenvalue decomposition? If so, what is it?

Yes, we do see a correspondence between V and evecs produced by eigenvalue decomposition. They both are same. The difference in sign need not worry us, as we can have $U\Sigma Vh = (-1)U\Sigma (-1)Vh$

## Relationship (if any) between the eigenvalues of $M^TM$ and the singular values of M?

Eigenvalues of $M^TM$ are squares of the singular values of M.