In [2]:
import numpy as np
from scipy import linalg

In [3]:
L = np.array([[4, -1, -1, -1, 0, 0, -1, 0], 
             [-1, 3, -1, -1, 0, 0, 0, 0], 
             [-1, -1, 3, -1, 0, 0, 0, 0], 
             [-1, -1, -1, 3, 0, 0, 0, 0], 
             [0, 0, 0, 0, 2, -1, -1, 0], 
             [0, 0, 0, 0, -1, 2, -1, 0], 
             [-1, 0, 0, 0, -1, -1, 4, -1], 
             [0, 0, 0, 0, 0, 0, -1, 1]])

In [4]:
U, s, Vh = linalg.svd(L, full_matrices=False)

In [5]:
s[:0:-1]

array([  7.50344604e-16,   3.54248689e-01,   1.00000000e+00,
         3.00000000e+00,   4.00000000e+00,   4.00000000e+00,
         4.00000000e+00])

In [21]:
Vh[-2]

array([-0.24701774, -0.38252766, -0.38252766, -0.38252766,  0.38252766,
        0.38252766,  0.24701774,  0.38252766])

In [19]:
np.sign(Vh[-2])

array([-1., -1., -1., -1.,  1.,  1.,  1.,  1.])